### ISSUE TITLE
How to Disable Menu 

### ISSUE THREAD

**Issue by chetanpanchal94** [keshavvishwkarma/KVRootBaseSideMenu-Swift#1]
How can we  disable menu on required view controller when needed?
because on every view controller pan gesture gets applied and menu gets opened
please help

**Comment by keshavvishwkarma** [comment]
Hi Chetanpanchal94 ,

Now you can use the **`allowPanGesture`** property of **`KVMenuContainerView`** class to disable  or enable the pan gesture. So you can disable  pan gesture from other root view controller by using below is the code -

> self.sideMenuViewController()?.menuContainerView?.allowPanGesture = false

**Note:** Doing this, It's become developer responsibility to manage enable/disable pan gesture according to requirement.

But My suggestion is that you should enable this property from **`viewDidAppear`** for all those view controller in which you want panning feature to open or close. 

```
override func viewDidAppear(animated: Bool) {
   self.sideMenuViewController()?.menuContainerView?.allowPanGesture = true 
}
```

And disable this property for all those view controller in which you do not want panning behavior.

```
override func viewDidAppear(animated: Bool) {
   self.sideMenuViewController()?.menuContainerView?.allowPanGesture = false 
}
```

**Comment by chetanpanchal94** [comment]
Hi keshavvishwkar,

Thank you for your update its working fine, you are correct its our
responsibility for this difficulty.

Thanks&Regards
Chetan Panchal

On Wed, Sep 28, 2016 at 3:42 PM, Keshav Vishwkarma <notifications@github.com
